// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpzdrwlqetbzwcmznmrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwemRyd2xxZXRiendjbXpubXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzExOTcsImV4cCI6MjA3NDU0NzE5N30.hUzEn5o-WHrjla8VKmjLq8vIts6TJgF4pOcScrBh0xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});